services:
  fxtumblr:
    build: .
    volumes:
      - ./fonts:/app/fonts
      - ./config.yml:/app/config.yml
      - fxtumblr-renders:/renders

  redis:
    image: redis:alpine

volumes:
  fxtumblr-renders:
